### ISSUE TITLE
opensesamerun.exe is not working

### ISSUE THREAD

**Issue by mariansauter** [open-cogsci/OpenSesame#607] opened 2018-03-07 10:45 UTC
Under Windows 10 and 8.1, the opensesamerun.exe is not working (Kafkaesque Koffka). 

``[Errno 9] Bad file descriptor``

If I indicate experimental path, it does not even open the miniversion with the above error message. If I don't indicate the experimental path ``""`` then it gives the error message when loading. **Indicating log-file path works perfectly, though!**

Does not work:
`"C:\Program Files (x86)\OpenSesame\opensesamerun.exe" "Y:\ZZ-Pilot_Main.osexp"`

Leading the path with an ``/`` or ``\`` works, but is no valid path of course :
`"C:\Program Files (x86)\OpenSesame\opensesamerun.exe" /Y:\ZZ-Pilot_Main.osexp"`

I'm guessing some kind of linux-to-windows transfer bug?

**Comment by smathot** [comment] 2018-03-07 13:34
Thanks for reporting this. I haven't figured out what causes it, but for now there is a simple workaround: Instead of calling `opensesamerun.exe`, start the script with Python: `python.exe Scripts\opensesamerun`. That seems to work.

**Comment by smathot** [comment] 2018-03-20 16:50
Fixed in https://github.com/smathot/OpenSesame-windows-launcher/commit/362871c72e631df639617a70e608cc44c4dcd392

**Comment by syu-id** [comment] 2018-06-06 12:39
Unfortunately this issue seems to persist with OpenSesame 3.2.4

![Error Screenshot](https://i.imgur.com/o9qeNsq.png)

Windows 10 version 1803

**Comment by smathot** [comment] 2018-07-18 15:23
@rongmu What do you do *exactly* to get this error message? And I'm assuming you're using a system with paths that contain non-ASCII characters. Could you help us by answering a few questions?

- What is your system's locale?
- What is the folder that contains `opensesamerun.exe`?
- What is your user-profile folder?
- Do you specify an experiment file, and if so, what's the path?

(I realize that folder names can be privacy sensitive, so you don't need to give them in full. As long as it's clear where and what kind of non-ASCII characters there are.)

**Comment by syu-id** [comment] 2018-07-19 08:38
@smathot 

Hi. This is what I do to reproduce the error on my Windows 10 laptop:

1. I open OpenSesame Run with the shortcut in my start menu
2. I specify the experiment file, log file, and subject number
3. Press Run. Then I get the error.

In fact I don't have non-ASCII characters in my paths, so I guess the error is caused by some other factors.

- My system locale: Japanese
- OpenSesame Run folder: C:\Program Files (x86)\OpenSesame
- User-profile folder: C:\Users\rongm
- Experiment file path is like: D:\Experiments\OpenSesame\my_experiment-1.osexp

Please let me know if you need further information.

**Comment by smathot** [comment] 2018-07-25 08:49
If you start opensesamerun in debug mode, the full error message (traceback) should be printed to the terminal. You can do this by opening the windows command prompt (`cmd.exe`) and then launching opensesamerun as follows (assuming OpenSesame is installed in the default folder):

![image](https://user-images.githubusercontent.com/594936/43189913-1480292a-8ff8-11e8-8523-cb23e7b0509d.png)

Could you post (a screenshot of) the full error message here?

**Comment by syu-id** [comment] 2018-07-25 11:02
Here is the full debug message.
Surprisingly, with debug mode OpenSesame Run loads the experiment file without problem.
(I just found that OpenSesame Run works fine if started from command line, even without the debug option. But the shortcut still won't work.)
I quitted the experiment with ESC + Q.

![opensesamerun-debug-1](https://user-images.githubusercontent.com/1129506/43196340-88ac3ccc-9042-11e8-8490-20db52de9ed7.PNG)
![opensesamerun-debug-2](https://user-images.githubusercontent.com/1129506/43196432-d0403520-9042-11e8-862a-47937e3cb1af.PNG)
![opensesamerun-debug-3](https://user-images.githubusercontent.com/1129506/43196446-d8894bfe-9042-11e8-9195-ec08aca0e861.PNG)

**Comment by smathot** [comment] 2018-07-25 12:43
> But the shortcut still won't work.

What do you mean with that?

**Comment by syu-id** [comment] 2018-07-25 13:12
I mean the "[Errno 9] Bad file descriptor" error still occurs if I start OpenSesame Run with the start menu shortcut.

**Comment by smathot** [comment] 2018-07-26 09:33
Fixed it! It was actually a bug in the installer, rather than the software itself. It should be fixed in 3.2.5 when it's released.

**Closed as completed by smathot** 2018-07-26 09:33 UTC
Labels: Bug
