### ISSUE TITLE
Experiments created on OSX, can't be opened on Windows

### ISSUE THREAD

**Issue by eort** [open-cogsci/OpenSesame#602] opened 2018-02-28 08:22 UTC
[This discussion](http://forum.cogsci.nl/index.php?p=/discussion/comment/13130#Comment_13130) on the forum suggests that the experiment path is operating system specific and causes crashes if the experimental file is moved across operating systems. 

I have no easy access to a Windows computer, so I can't check or reproduce the problem.

**Comment by smathot** [comment] 2018-03-01 10:16
@dschreij Could you see if you can reproduce this?

**Comment by dschreij** [comment] 2018-03-20 22:01
I cannot reproduce this. I have created some (simple) experiments on Mac, and ran them on Windows afterwards without problems. I haven't tried using the file pool with images or something, so the problem might hide there and I can test this tomorrow if necessary. 
I think this case was spurious. There haven't been any reports on this since, have there? I'm sure many people create their experiments on one platform and run them on another, so if this was a common problem I would have expected to see more reports of this issue by now.

**Comment by smathot** [comment] 2018-03-21 09:28
I suspected as much. Let's close this.

**Closed as completed by smathot** 2018-03-21 09:28 UTC
Labels: Unverified
